services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./src:/app/src
      - ./next.config.js:/app/next.config.js
      - ./tailwind.config.ts:/app/tailwind.config.ts
    networks:
      - client
  clientDB:
    container_name: clientDB
    image: postgres:16-alpine3.19
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data
    networks:
      - client
networks:
  client:
    name: client
