import { HydrationBoundary, dehydrate } from "@tanstack/react-query"
import type { Metadata } from "next"

import { getUsers } from "@/entities/user"

import { queryClient } from "@/shared/api"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function UsersLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	await queryClient.prefetchQuery({
		queryKey: ["users"],
		queryFn: () => getUsers(),
	})
	return (
		<HydrationBoundary state={dehydrate(queryClient)}>
			<main>{children}</main>
		</HydrationBoundary>
	)
}
